### ISSUE TITLE
Ist es möglich das auch mit Docker auf einem Synology NAS zu verwenden?

### ISSUE THREAD

**Issue by trichte** [thgau/goodwe_modbus#1]
Hi! Ich habe auch einen Goodwe Wechselrichter und ich versuche EVCC auf dem Synologay NAS im Docker Container zum laufen zu bringen.

Mein Goodwe hat aber nur den WIFI Stick.
Jetzt ist die Frage, ob man die Funktion auch für Docker nutzen kann.

viele Grüße 
Thomas

**Comment by thgau** [comment]
Klar, das geht sicherlich auch. Ich versuche mal die Tage ein image zu bauen und die Schritte zu dokumentieren.

**Comment by trichte** [comment]
Das wäre super

**Comment by thgau** [comment]
Hallo Thomas,
ich kann die Kombination leider nicht selbst testen, da der Goodwe bei einem Freund steht und dort hab ich aber keine Docker Umgebung. Und ein UDP Tunnel ist mir jetzt zu aufwändig. Daher musst du selbst testen. Das Image ist unter thgau/goodwe_modbus:latest zu finden. Falls du Docker-Compose benutzt (was ich nur empfehlen kann, nutze es selbst auch bei der Synology. Geht aber aber nur per Shell), kannst du das docker-compose.yml hier aus dem git verwenden. Du musst dann noch eine Datei namens .env anlegen und dort eine Zeile reinschreiben:
GOODWE_IP=\<ip addresse des goodwe>
In der evcc.yaml dann statt localhost den Namen "goodwe_modbus" verweden.
Falls du nicht mit compose arbeitest, musst du in der evcc.yaml statt localhost den Namen deiner Synology verwenden.
Bei Problemen oder Fragen bitte melden...
Grüße, Thomas

**Comment by trichte** [comment]
Danke … Ich probiere das am Freitag

**Comment by trichte** [comment]
Guten Morgen Thomas,

ich habe es eben ausprobiert. Ich selber nutze nur Docker ohne Docker-Compose.

Ich konnte den Container im Docker herunterladen.
Als ersten Test habe ich den Conatiner einfach mal gestartet. Dann erhalte ich die Fehlermeldung
_argument ip-address missing_

Danach habe ich eine Datei Goodwe.env angelegt und dort die IP hinterlegt.
GOODWE_IP=192.168.178.88
Die Datei habe den Continer als Mount hinzugewiesen, wie das auch bei der YAML Datei ist.
Ich erhalte aber weiter die Fehlermeldung
_argument ip-address missing_

Mache ich noch irgendwas falsch?

Viele Grüße
Thomas

**Comment by thgau** [comment]
Hallo Thomas,
du kannst nicht eine Datei mit Environmentvariablen einfach als Mount benutzten. Wenn du ohne compose arbeitest musst du die Variable direkt dem Docker-Run mit geben (docker run -eGOODWE_IP=192.168.178.88 thgau/goodwe_modbus:latest), bzw. in der Synology beim Erstellen des Containers unter "Allgemeine Einstellungen" auf den Knopf "Erweiterte Einstellungen" gehen und dort eintragen:
![grafik](https://github.com/thgau/goodwe_modbus/assets/7081245/2e279645-bb46-4913-b89c-0deb4f926177)
Achte auch darauf, dass der Port explizit auf 8899 weitergeleitet wird und nicht eine zufällige Nummer gewählt wird
![grafik](https://github.com/thgau/goodwe_modbus/assets/7081245/f8dd80b0-ba47-42e7-a7f8-c0f7acd3570e)

Viele Grüße, Thomas

**Comment by trichte** [comment]
Besten den Container habe ich zum laufen bekommen.

Nur den Port kann ich nicht hinterlegen:

![grafik](https://github.com/thgau/goodwe_modbus/assets/47119147/af40000c-4265-4b4e-8850-267238d7532d)

Im EVCC habe ich jetzt die IP der Synology hinterlegt. Da bekomme ich aber timeouts.
![grafik](https://github.com/thgau/goodwe_modbus/assets/47119147/308d033f-7b4a-4bdd-b8ec-b83b17bb1f4d)

**Comment by thgau** [comment]
Wenn der Container sich nicht beendet, dann hat er zumindest mal mit dem Goodwe Kontakt aufnehmen können. Soweit schon mal gut.
Stimmen die IP Addressen in der EVCC config? Eine typische Fritzbox-Adresse ist 192.168.178.xx . In deiner Fehlermeldung sind aber 178 und 168 vertauscht...

**Comment by trichte** [comment]
Ja du hattest recht, das war natürlich im EVCC vertauscht. Das habe ich korrigiert.
Ich habe aber weiterhin timeouts.

**Comment by thgau** [comment]
Du hattest ja Probleme mit der Port-Einstellung. Wenn der Port nicht exponiert wird, kann keine Verbindung zustande kommen.
Gehen wir die Erstellung des Containers noch mal Schritt für Schritt durch:
![grafik](https://github.com/thgau/goodwe_modbus/assets/7081245/77bd97a3-2520-4c1c-bdb5-123240b50703)

![grafik](https://github.com/thgau/goodwe_modbus/assets/7081245/0c9930aa-a8dc-4115-a13d-eee9fa0e0543)

![grafik](https://github.com/thgau/goodwe_modbus/assets/7081245/ef165287-c5ee-42f0-920f-1297a1b94703)

![grafik](https://github.com/thgau/goodwe_modbus/assets/7081245/60ddac20-815b-4d8e-b0aa-c3a4b8348c32)
Kannst du das so nochmal nachvollziehen?

**Comment by trichte** [comment]
Ich hatte den Container im Host Modus laufen, wie man das auch bei EVCC machen sollte. Jetzt habe ich das auf Bridge geändert.
Damit konnte ich jetzt auch den Port pflegen.

Allerdings habe ich jetzt diverse Fehler im Protokoll
![grafik](https://github.com/thgau/goodwe_modbus/assets/47119147/9cfd78f4-0872-4020-9471-d33be3c70bbd)

**Comment by thgau** [comment]
Okay, Host Modus hatte ich jetzt nicht auf dem Radar.
Sehe gerade, dass ich den Port auf localhost binde, und das könnte das Problem sein.

Als Lösung könnte das so gehen:
goodwe_modbus doch wieder auf Host Mode und in der evcc.yml auch wieder "localhost" statt IP-Adresse. Wenn beide Container im Host Mode laufen, dass sollte die Verbindung per localhost gehen.

**Comment by trichte** [comment]
Hallo Thomas,

Ich habe den Container jetzt als Host laufen und habe in die evcc.yaml das als localhost eingetragen und den Port auf 5001 gesetzt. Jetzt lauft der MODBUS wieder und auch das EVCC. Jetzt habe ich aber eine neu Fehlermeldung.

![grafik](https://github.com/thgau/goodwe_modbus/assets/47119147/06c31384-c291-4c43-8837-8805177009a3)

**Comment by thgau** [comment]
Wie kommst du jetzt auf Port 5001? Es sollte schon noch 8899 sein. Wenn beide Container auf HostMode laufen, ist das ja wie lokal installiert und damit sollte es wie im ursprünglich beschrieben gehen. EVCC verbindet sich per TCP localhost:8899 zum goodwe_modbus und dieser per UDP \<goodwe-ip>:8899 zum GoodWe.

**Comment by trichte** [comment]
Vielen lieben Dank für deine Geduld. Jetzt läuft es :-)

So nochmal für andere als Zusammenfassung
- Container im Docker herunterladen

![grafik](https://github.com/thgau/goodwe_modbus/assets/47119147/eeb19eef-6cb6-4c2b-a1d3-e459151c895d)

- Container als Host einplanen

![grafik](https://github.com/thgau/goodwe_modbus/assets/47119147/98ea3018-b494-4eb3-ac3c-7388f721a243)

- In den erweiterten Einstellungen den Parameter GOOWE_IP mit der IP von deinem Goodwe Wechselrichter hinzufügen

![grafik](https://github.com/thgau/goodwe_modbus/assets/47119147/10f28a1d-915c-41cd-96ea-1328a34f084e)
![grafik](https://github.com/thgau/goodwe_modbus/assets/47119147/4e118fb1-540a-4ef8-8b1a-b71ffbb932e5)

- Dann einfach immer weiter klicken und den Container starten.

Im EVCC.YAML dann bei den Goodwe Geräten **localhost** und den **Port 8899** eintragen.
Das sieht dann so aus. 

![grafik](https://github.com/thgau/goodwe_modbus/assets/47119147/df8fc826-2b5e-41d3-b0f2-dbc1613a83ad)


Mit dieser Konfiguration läuft der Goodwe Wechselrichter mit EVCC auch wenn man nur den WLAN stick hat.

**Comment by thgau** [comment]
Prima. Danke auch für dein geduldiges Ausprobieren.
